spring:
  application:
    name: test-fbs
  redis:
    host: 192.168.159.154
    port: 6379
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.159.154:3306/test_fbs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      validation-query: select 1
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.testfbs.entity
server:
  port: 8881